### ISSUE TITLE
Client Timeout in Solo

### ISSUE THREAD

**Issue by Ch0wW** [fgsfdsfgs/nxquake2#3] opened 2019-03-18 09:28 UTC
After waiting too long in singleplayer (aka : don't move/aim/anything), nxQuake2 says the client has timed out, and will shortly reload the map, losing all of our inventory. It can even occur while waiting a bit in the HOME menu, or putting the Switch into sleep mode.

Since the solo shouldn't rely on a server, timeouts shouldn't even occur.

I'll try tonight If this issue is also happening on YamagiQ2.

**Comment by fgsfdsfgs** [comment] 2019-03-18 14:49
Actually that's exactly how solo works, it runs a local server with `maxplayers = 1` and connects to it via internal loopback. However it should not time out local clients, so that's definitely a bug. How long did you have to wait until you got dropped? I can't seem to get it to happen.

**Comment by Ch0wW** [comment] 2019-03-19 21:29
I have absolutely no idea. It can take 5 minutes, maybe ? I haven't counted up actually.

**Comment by fgsfdsfgs** [comment] 2019-03-19 21:54
It might time out if you minimize the game because some timers don't update or something. I tried and couldn't get it to, waited for like 5-10 minutes.

**Comment by fgsfdsfgs** [comment] 2019-04-02 14:34
Confirmed, it times out when the game is minimized for about 5 minutes, precisely because it fucks up the timers. Not sure what would be the "cleanest" way to fix that.
UPD: the cleanest way would be to pause the game while it's minimized. Gonna try to do that.

**Comment by fgsfdsfgs** [comment] 2019-04-02 15:52
Hopefully fixed in b4435a3.

**Closed as completed by fgsfdsfgs** 2019-04-02 15:52 UTC
